### PR TITLE
Adding Package.json for NPM

### PR DESCRIPTION
**Pull request by thepauleh**
This adds a package.json so this can go into npm

I've added the package here:
https://www.npmjs.com/package/highlightjs

Let me know any npmjs usernames that you'd like added to contributors

### CODE REVIEW

**Comment by RobLoach** [comment]
https://www.npmjs.com/package/highlight.js ?

Usually the syntax for a component on npm is `component-%name`.

**Comment by RobLoach** [comment]
@thepauleh Could you add myself and a few other maintainers to the package? `9.2.0` is out.

**Comment by thepauleh** [comment]
HI Rob - i've added a couple of people to the project - can't find you on npmjs?

**Comment by RobLoach** [comment]
@thepauleh Thanks! I should be `robloach` on there https://www.npmjs.com/~robloach

Thanks again! Glad this got pushed forwards.

**Pull request merged**
